stderr of test 'python-connections-Bug.2901` in directory 'sql/test/BugTracker-2011` itself:


# 17:16:09 >  
# 17:16:09 >  "mserver5" "--debug=10" "--set" "gdk_nr_threads=0" "--set" "gdk_dbfarm=/ufs/sjoerd/Monet-stable/var/MonetDB" "--set" "mapi_open=true" "--set" "mapi_port=36960" "--set" "monet_prompt=" "--trace" "--forcemito" "--set" "mal_listing=2" "--dbname=mTests_test_BugTracker-2011" "--set" "mal_listing=0"
# 17:16:09 >  

# builtin opt 	gdk_dbname = demo
# builtin opt 	gdk_dbfarm = /ufs/sjoerd/Monet-stable/var/monetdb5/dbfarm
# builtin opt 	gdk_debug = 0
# builtin opt 	gdk_alloc_map = no
# builtin opt 	gdk_vmtrim = yes
# builtin opt 	monet_prompt = >
# builtin opt 	monet_daemon = no
# builtin opt 	mapi_port = 50000
# builtin opt 	mapi_open = false
# builtin opt 	mapi_autosense = false
# builtin opt 	sql_optimizer = default_pipe
# builtin opt 	sql_debug = 0
# cmdline opt 	gdk_nr_threads = 0
# cmdline opt 	gdk_dbfarm = /ufs/sjoerd/Monet-stable/var/MonetDB
# cmdline opt 	mapi_open = true
# cmdline opt 	mapi_port = 36960
# cmdline opt 	monet_prompt = 
# cmdline opt 	mal_listing = 2
# cmdline opt 	gdk_dbname = mTests_test_BugTracker-2011
# cmdline opt 	mal_listing = 0

# 17:16:09 >  
# 17:16:09 >  "/usr/bin/python" "python-connections-Bug.2901.SQL.py" "python-connections-Bug.2901"
# 17:16:09 >  


# 17:16:10 >  
# 17:16:10 >  "Done."
# 17:16:10 >  

