stderr of test 'global_table_propagation.Bug-6846` in directory 'sql/test/BugTracker-2020` itself:


# 19:18:33 >  
# 19:18:33 >  "/usr/bin/python3" "global_table_propagation.Bug-6846.py" "global_table_propagation.Bug-6846"
# 19:18:33 >  

SELECT: no such table 'close_d'

# 19:18:34 >  
# 19:18:34 >  "Done."
# 19:18:34 >  

