stderr of test 'grant-role-not-idempotent.Bug-6660` in directory 'sql/test/BugTracker-2018` itself:


# 17:35:19 >  
# 17:35:19 >  "/usr/bin/python2" "grant-role-not-idempotent.Bug-6660.py" "grant-role-not-idempotent.Bug-6660"
# 17:35:19 >  

MAPI  = (mydummyuser) /var/tmp/mtest-4265/.s.monetdb.32462
QUERY = set role "sysadmin"; --error
ERROR = !Role (sysadmin) missing
CODE  = 42000
MAPI  = (monetdb) /var/tmp/mtest-30651/.s.monetdb.34282
QUERY = grant "sysadmin" to "mydummyuser"; --error
ERROR = !GRANT: User 'mydummyuser' already has ROLE 'sysadmin'
CODE  = M1M05
MAPI  = (monetdb) /var/tmp/mtest-30651/.s.monetdb.34282
QUERY = revoke "sysadmin" from "mydummyuser"; --error
ERROR = !REVOKE: User 'mydummyuser' does not have ROLE 'sysadmin'
CODE  = 01006

# 17:35:20 >  
# 17:35:20 >  "Done."
# 17:35:20 >  

