stderr of test 'pyapi3_19` in directory 'sql/backends/monet5/UDF/pyapi3` itself:


# 11:59:04 >  
# 11:59:04 >  "mserver5" "--debug=10" "--set" "gdk_nr_threads=0" "--set" "mapi_open=true" "--set" "mapi_port=35428" "--set" "mapi_usock=/var/tmp/mtest-5346/.s.monetdb.35428" "--set" "monet_prompt=" "--forcemito" "--set" "mal_listing=2" "--dbpath=/home/mytherin/opt/var/MonetDB/mTests_sql_backends_monet5" "--set" "mal_listing=0" "--set" "embedded_r=true" "--set" "embedded_py=true"
# 11:59:04 >  

# builtin opt 	gdk_dbpath = /home/mytherin/opt/var/monetdb5/dbfarm/demo
# builtin opt 	gdk_debug = 0
# builtin opt 	gdk_vmtrim = no
# builtin opt 	monet_prompt = >
# builtin opt 	monet_daemon = no
# builtin opt 	mapi_port = 50000
# builtin opt 	mapi_open = false
# builtin opt 	mapi_autosense = false
# builtin opt 	sql_optimizer = default_pipe
# builtin opt 	sql_debug = 0
# cmdline opt 	gdk_nr_threads = 0
# cmdline opt 	mapi_open = true
# cmdline opt 	mapi_port = 35428
# cmdline opt 	mapi_usock = /var/tmp/mtest-5346/.s.monetdb.35428
# cmdline opt 	monet_prompt = 
# cmdline opt 	mal_listing = 2
# cmdline opt 	gdk_dbpath = /home/mytherin/opt/var/MonetDB/mTests_sql_backends_monet5
# cmdline opt 	mal_listing = 0
# cmdline opt 	embedded_r = true
# cmdline opt 	embedded_py = true
# cmdline opt 	gdk_debug = 536870922

# 11:59:04 >  
# 11:59:04 >  "mclient" "-lsql" "-ftest" "-Eutf-8" "-i" "-e" "--host=/var/tmp/mtest-5346" "--port=35428"
# 11:59:04 >  


# 18:08:01 >  
# 18:08:01 >  Mtimeout -timeout 60 mclient -lsql -ftest -Eutf-8 -i -e --host=/var/tmp/mtest-24131 --port=30465 < /Users/myth/Programs/MonetDB/sql/backends/monet5/UDF/pyapi3/../../Tests/pyapi19.sql
# 18:08:01 >  

MAPI  = (monetdb) /var/tmp/mtest-24131/.s.monetdb.30465
QUERY = SELECT * FROM mapped_query();
ERROR = !Python exception
        !
        !  1. def pyfun(_columns,_column_types,_conn):
        !> 2.   _conn.execute('CREATE TABLE pyapi19_integers(i INTEGER);')
        !  3.   _conn.execute('INSERT INTO pyapi19_integers VALUES (0), (1), (2);')
        !  4.   return(1)
        !Loopback queries are not supported in parallel.
CODE  = PY000
MAPI  = (monetdb) /var/tmp/mtest-13372/.s.monetdb.36607
QUERY = SELECT * FROM pyapi19_integers;
ERROR = !Current transaction is aborted (please ROLLBACK)
CODE  = 25005
MAPI  = (monetdb) /var/tmp/mtest-13372/.s.monetdb.36607
QUERY = CREATE FUNCTION mapped_result_query() returns table (i integer) LANGUAGE PYTHON_MAP
        {
            res = _conn.execute('SELECT * FROM pyapi19_integers;')
            return res['i']
        };
ERROR = !Current transaction is aborted (please ROLLBACK)
CODE  = 25005
MAPI  = (monetdb) /var/tmp/mtest-13372/.s.monetdb.36607
QUERY = SELECT * FROM mapped_result_query();
ERROR = !Current transaction is aborted (please ROLLBACK)
CODE  = 25005
MAPI  = (monetdb) /var/tmp/mtest-13372/.s.monetdb.36607
QUERY = SELECT COUNT(i) FROM pyapi19_load_table();
ERROR = !Python exception
        !
        !  1. def pyfun(_columns,_column_types,_conn):
        !> 2.   res = _conn.execute('SELECT * FROM pyapi19_integers;')
        !  3.   return res['i']
        !  4. 
        !Loopback queries are not supported in parallel.
CODE  = PY000
MAPI  = (monetdb) /var/tmp/mtest-13372/.s.monetdb.36607
QUERY = SELECT * FROM mapped_result_query();
ERROR = !Python exception
        !
        !  1. def pyfun(_columns,_column_types,_conn):
        !> 2.   res = _conn.execute('SELECT * FROM pyapi19_strings;')
        !  3.   return res['s']
        !  4. 
        !Loopback queries are not supported in parallel.
CODE  = PY000
MAPI  = (monetdb) /var/tmp/mtest-13372/.s.monetdb.36607
QUERY = SELECT * FROM mapped_result_query();
ERROR = !Python exception
        !
        !  1. def pyfun(_columns,_column_types,_conn):
        !> 2.   res = _conn.execute('SELECT * FROM pyapi19_dates;')
        !  3.   return res
        !  4. 
        !Loopback queries are not supported in parallel.
CODE  = PY000
MAPI  = (monetdb) /var/tmp/mtest-13372/.s.monetdb.36607
QUERY = SELECT * FROM pyapi19_load_table() LIMIT 100;
ERROR = !Python exception
        !
        !  1. def pyfun(_columns,_column_types,_conn):
        !> 2.   res = _conn.execute('SELECT * FROM pyapi19_integers;')
        !  3.   return res
        !  4. 
        !Loopback queries are not supported in parallel.
CODE  = PY000

# 18:08:01 >  
# 18:08:01 >  "Done."
# 18:08:01 >  

