stderr of test 'python3_dbapi` in directory 'sql/test/mapi` itself:


# 22:24:36 >  
# 22:24:36 >  Mtimeout -timeout 300  Mserver "--config=/ufs/niels/scratch/rc/Linux-x86_64/etc/MonetDB.conf" --debug=10 --set "monet_mod_path=/ufs/niels/scratch/rc/Linux-x86_64/lib/MonetDB4:/ufs/niels/scratch/rc/Linux-x86_64/lib/MonetDB4/lib:/ufs/niels/scratch/rc/Linux-x86_64/lib/MonetDB4/bin" --set "gdk_dbfarm=/ufs/niels/scratch/rc/Linux-x86_64/var/MonetDB4/dbfarm" --set "sql_logdir=/ufs/niels/scratch/rc/Linux-x86_64/var/MonetDB4/sql_logs" --set "xquery_logdir=/ufs/niels/scratch/rc/Linux-x86_64/var/MonetDB4/xquery_logs" --set mapi_open=true --set xrpc_open=true --set mapi_port=33515 --set xrpc_port=46441 --set monet_prompt= --trace "--dbname=mTests_src_test_mapi" --dbinit=" module(sql_server);" ; echo ; echo Over..
# 22:24:36 >  


# 22:24:36 >  
# 22:24:36 >  Mtimeout -timeout 180 ./python_dbapi.SQL.sh python_dbapi 
# 22:24:36 >  


# 22:24:36 >  
# 22:24:36 >  sqlsample.py 33515 mTests_src_test_mapi
# 22:24:36 >  


# 22:24:36 >  
# 22:24:36 >  Done.
# 22:24:36 >  

